### ISSUE TITLE
Had a query regarding the data folder

### ISSUE THREAD

**Issue by Atifbeast** [carolinedlu/llamaindex-chat-with-streamlit-docs#3]
Heyy, I was actually wondering that how to convert an entire website's data into an (.md) file or into any other format accepted by llama-index ! I plan to organize a workshop on llama-index and streamlit in my Uni, So thought of using my Uni website as an input to llama-index... Or can it only be done by individual's who host the websites ? Thank-you

**Comment by carolinedlu** [comment]
Hey @Atifbeast, it looks like you could use the ["Simple Website Loader" from LlamaHub](https://llamahub.ai/l/web-simple_web) for this!
