### ISSUE TITLE
Import Error with llama-index

### ISSUE THREAD

**Issue by ssfriedman1** [carolinedlu/llamaindex-chat-with-streamlit-docs#6]
Hi,

I was trying to fork this project from the original interface posted and before editing it in codespaces, I get:

ImportError: cannot import name 'VectorStoreIndex' from 'llama_index' (unknown location)

I was able to get it to work yesterday morning, but have been unable to find a bug in my code to account for it. Please let me know if you can help!
<img width="936" alt="Screenshot 2024-02-13 at 12 40 38" src="https://github.com/carolinedlu/llamaindex-chat-with-streamlit-docs/assets/96848421/1fd442de-fbb6-45a7-9056-03ea809ff737">

**Comment by raoqu** [comment]
llama_index v0.10 adjusts the package structure, and you can make the following modifications to the code:
```python
from llama_indeximport VectorStoreIndex --> from llama_index.core ...
from llama_index.llms import OpenAI --> from llama_index.llms.openai ...
```

**Comment by ssfriedman1** [comment]
Thanks for the help! Which version of llama-index would be best to maintain the old structure?

**Comment by bruchpilot123** [comment]
Hello, same Issue for me! I tried now version 9 of llamaindex, which also did not work. 

 Unfortunately I am also not able to run the migration tool, since I am getting the following issue:
 ImportError: cannot import name 'SimpleDirectoryReader' from 'llama_index.core' (unknown location)

Any help is appreciated. Have a good day.

**Comment by dhruvaditya** [comment]
> Hello, same Issue for me! I tried now version 9 of llamaindex, which also did not work.
> 
> Sadly I was to stupid to change the code as suggested by @raoqu.
> 
> Unfortunately I am also not able to run the migration tool, since I am getting the following issue: ImportError: cannot import name 'SimpleDirectoryReader' from 'llama_index.core' (unknown location)
> 
> Any help is appreciated. Have a good day.

Solution: 
There are some recent change in llama index like llama_index is llama_index.core , Here you can try these ways:

there may be installation issue, so you can install again, [pip install llama-index].  if the problem still persist then try to create a new virtual environments and install requirements.txt by this command pip install -r requirements.txt
Then try this code, Most probably your problem will be solved. 

from llama_index.core import SimpleDirectoryReader

reader = SimpleDirectoryReader(input_dir="path/to/directory")
documents = reader.load_data()

Have a great day.

**Comment by carolinedlu** [comment]
Apologies for the delay! I just updated the repo to account for the 0.10.0 update of LlamaIndex. Note that you might need to start with a fresh environment if you're running the app locally.
